package objectClass;

public class EmployeeDriver {
	public static void main(String[] args) {
		Employee employee1 = new Employee("Anwesa", 1, 50000);
//		System.out.println(employee1);
//		System.out.println(employee1.toString());
		
		Employee employee2 = new Employee("Anwesa", 1, 50000);
//		System.out.println(employee1 == employee2);
//		System.out.println(employee1.equals(employee2));
		
		System.out.println(employee1.hashCode()); //hashCode generated by the reference of their object
		System.out.println(employee2.hashCode());
		
		String s = "Anwesa";
		System.out.println(s.hashCode());
		
	}
}
